
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT PRIMARY KEY,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT,
    PRICE REAL
);


INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
('1', 'Chai', '1', '1', '10 boxes x 20 bags', 18),
('2', 'Chang', '1', '1', '24 - 12 oz bottles', 19),
('3', 'Aniseed Syrup', '1', '2', '12 - 550 ml bottles', 10),
('4', 'Chef Anton Seasoning', '2', '2', '48 - 6 oz jars', 22),
('5', 'Chef Anton Mix', '2', '2', '36 boxes', 20);


SELECT * FROM PRODUCTS;


SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;


SELECT AVG(PRICE) AS Average_Price
FROM PRODUCTS;


SELECT SUM(PRICE) AS Total_Price
FROM PRODUCTS;


SELECT MIN(PRICE) AS Minimum_Price
FROM PRODUCTS;


SELECT MAX(PRICE) AS Maximum_Price
FROM PRODUCTS;


SELECT CATEGORY_ID,
       COUNT(*) AS Product_Count
FROM PRODUCTS
GROUP BY CATEGORY_ID;


SELECT CATEGORY_ID,
       AVG(PRICE) AS Average_Price
FROM PRODUCTS
GROUP BY CATEGORY_ID;